### ISSUE TITLE
NoSuchMethodError: org.apache.spark.sql.SQLContext.createDataFrame

### ISSUE THREAD

**Issue by jlandahl** [tweag/sparkle#105]
When running the `dataframe` example app, I get the following:

```
$ stack --nix exec -- spark-submit --master 'local[*]' sparkle-example-dataframe.jar
bash: /nix/store/c7p144r67arkwdknchxan87vmywlnzjh-ncurses-5.9/lib/libtinfo.so.5: no version information available (required by bash)
17/04/12 13:49:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/04/12 13:49:35 WARN Utils: Your hostname, jpl-ubuntu resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
17/04/12 13:49:35 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.createDataFrame(Lorg/apache/spark/api/java/JavaRDD;Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/DataFrame;
	at Helper.toDF(Helper.java:40)
	at io.tweag.sparkle.SparkMain.invokeMain(Native Method)
	at io.tweag.sparkle.SparkMain.main(SparkMain.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
sparkle-worker: JVMException (J 0x00007fe4d8fe0040)
```

Is this a known problem?

**Comment by mboes** [comment]
Good catch. @facundominguez it seems that the type signature for `createDataFrame` silently changed between Spark 1.6 and Spark 2.0?

**Comment by facundominguez** [comment]
Spark 2 has no DataFrame class anymore IIRC. The sparkle bindings would need to be changed to use Datasets.

**Comment by jlandahl** [comment]
It looks like starting in 2.0 that method (`SQLContext.createDataFrame`) is now returning a `Dataset<Row>` where before it returned a `DataFrame`: https://spark.apache.org/docs/2.0.1/api/java/org/apache/spark/sql/SQLContext.html#createDataFrame(org.apache.spark.api.java.JavaRDD,%20org.apache.spark.sql.types.StructType)

**Comment by mboes** [comment]
Right. So the binding needs to be updated. Should be a straightforward change.

**Comment by rajeshbalel** [comment]
Is there a generic way to get this changed for all code migration from spark 1.6 to 2.0
please comment

**Comment by facundominguez** [comment]
The dataframe example is now running successfully in CI.
