### ISSUE TITLE
unsatisafied link error:libHelloWorld.so: cannot dynamically load executable

### ISSUE THREAD

**Issue by sonbho** [tweag/sparkle#142]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/manbub1/sonali/libHelloWorld.so: /home/manbub1/sonali/libHelloWorld.so: cannot dynamically load executable
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at HelloWorld.<clinit>(HelloWorld.java:6)

**Comment by facundominguez** [comment]
Hello @sonbho. It will be difficult to help you unless we have most of the details of how libHelloWorld.so has been created.

Did the hello example work for you?
https://github.com/tweag/sparkle/blob/master/README.md

**Comment by facundominguez** [comment]
Closing due to inactivity. But please, feel free to reopen.
