### ISSUE TITLE
Can't map over Ints

### ISSUE THREAD

**Issue by nh2** [tweag/sparkle#50]
I'm trying to run this sparkle program that maps `+ 1` over `[1..10]`:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StaticPointers #-}

module Main where

import Control.Distributed.Closure
import Control.Distributed.Spark as RDD

main :: IO ()
main = do
    conf <- newSparkConf "sparkle pure"
    sc   <- getOrCreateSparkContext conf

    l <- parallelize sc [1..10::Int]
    nums <- RDD.map (closure (static succ)) l >>= RDD.collect
    print nums
```

But I get the error `java.lang.NoSuchMethodError: longValue`.

--

Full output:

```
% stack --nix build hello && stack --nix exec -- sparkle package sparkle-example-hello && stack --nix exec -- spark-submit --master 'local[1]' sparkle-example-hello.jar       
Loading Sparkle application ...
Application loaded.
16/08/10 16:06:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/08/10 16:06:53 WARN Utils: Your hostname, ares resolves to a loopback address: 127.0.1.1; using 192.168.1.100 instead (on interface eth0)
16/08/10 16:06:53 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Exception in thread "Executor task launch worker-0" java.lang.NoSuchMethodError: longValue
	at io.tweag.sparkle.Sparkle.apply(Native Method)
	at io.tweag.sparkle.function.HaskellFunction.call(HaskellFunction.java:14)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1015)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
: JavaException (J 0x00007f922c000f40)
```

**Comment by mboes** [comment]
Oops! This is due to a small typo in the `Reify Int ('Class "java.lang.Integer")` instance. The patch to fix this is a one character change. Fortunately we should be able to implement these instances using the more recent `call` function, rather than raw JNI calls, making this kind of typo pretty much impossible.
